# 构建 VitePress 站点并将其部署到 GitHub Pages 的示例工作流程
#
name: Deploy to GitHub Pages

on:
  # 在针对 `main` 分支的推送上运行
  push:
    branches: [main]
  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: List files
        run: ls -la
      - name: Build
        run: npm run docs:build
      - name: List dist directory
        run: |
          echo "检查dist目录内容:"
          ls -la docs/.vitepress/dist || echo "dist目录不存在!"
          echo "检查config文件:"
          cat docs/.vitepress/config.js
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          force_orphan: true 